<?php

	//application details
		$apps[$x]['name'] = "BulkVS";
		$apps[$x]['uuid'] = "5557cc3b-2956-4636-8581-f77a126f67f4";
		$apps[$x]['category'] = "Switch";
		$apps[$x]['subcategory'] = "";
		$apps[$x]['version'] = "1.0";
		$apps[$x]['license'] = "Mozilla Public License 1.1";
		$apps[$x]['url'] = "http://www.fusionpbx.com";
		$apps[$x]['description']['en-us'] = "Integrate with BulkVS API to manage phone numbers, update Portout PIN and CNAM, and purchase new numbers.";
		$apps[$x]['description']['en-gb'] = "Integrate with BulkVS API to manage phone numbers, update Portout PIN and CNAM, and purchase new numbers.";
		$apps[$x]['description']['ar-eg'] = "";
		$apps[$x]['description']['de-at'] = "";
		$apps[$x]['description']['de-ch'] = "";
		$apps[$x]['description']['de-de'] = "";
		$apps[$x]['description']['el-gr'] = "";
		$apps[$x]['description']['es-cl'] = "";
		$apps[$x]['description']['es-mx'] = "";
		$apps[$x]['description']['fr-ca'] = "";
		$apps[$x]['description']['fr-fr'] = "";
		$apps[$x]['description']['he-il'] = "";
		$apps[$x]['description']['it-it'] = "";
		$apps[$x]['description']['ka-ge'] = "";
		$apps[$x]['description']['nl-nl'] = "";
		$apps[$x]['description']['pl-pl'] = "";
		$apps[$x]['description']['pt-br'] = "";
		$apps[$x]['description']['pt-pt'] = "";
		$apps[$x]['description']['ro-ro'] = "";
		$apps[$x]['description']['ru-ru'] = "";
		$apps[$x]['description']['sv-se'] = "";
		$apps[$x]['description']['uk-ua'] = "";

	//default settings
		$y=0;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "d4e8275b-5dba-4d07-a5be-2e10fe13f74d";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "bulkvs";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "api_key";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "BulkVS API Key/Username";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "2baa6433-08df-466e-b1b1-f3a14c082dd5";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "bulkvs";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "api_secret";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "BulkVS API Secret";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "2d25170d-03cd-4998-81d2-f7da041acdcf";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "bulkvs";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "trunk_group";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Trunk Group to filter numbers";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "96c1b551-7ff4-48e4-8e10-da513aae84b3";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "bulkvs";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "api_url";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "https://portal.bulkvs.com/api/v1.0";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "BulkVS API Base URL";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "a8f3c2d1-4e5b-6c7d-8e9f-0a1b2c3d4e5f";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "bulkvs";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "http_secret";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "BulkVS HTTP Secret (for LRN & CNAM lookup)";
		$y++;
		$apps[$x]['default_settings'][$y]['default_setting_uuid'] = "b9e4d3c2-5f6c-7d8e-9f0a-1b2c3d4e5f6a";
		$apps[$x]['default_settings'][$y]['default_setting_category'] = "bulkvs";
		$apps[$x]['default_settings'][$y]['default_setting_subcategory'] = "park_domain";
		$apps[$x]['default_settings'][$y]['default_setting_name'] = "text";
		$apps[$x]['default_settings'][$y]['default_setting_value'] = "";
		$apps[$x]['default_settings'][$y]['default_setting_enabled'] = "true";
		$apps[$x]['default_settings'][$y]['default_setting_description'] = "Park Domain - Domain name to use when parking numbers without a domain";

	//permission details
		$y=0;
		$apps[$x]['permissions'][$y]['name'] = "bulkvs_view";
		$apps[$x]['permissions'][$y]['menu']['uuid'] = "48e8090a-7e28-44fc-9239-b3a6511c477f";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "bulkvs_edit";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "bulkvs_search";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "bulkvs_purchase";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "bulkvs_e911";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "bulkvs_e911_server";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";
		$y++;
		$apps[$x]['permissions'][$y]['name'] = "bulkvs_e911_all";
		$apps[$x]['permissions'][$y]['groups'][] = "superadmin";

	//schema details - Numbers cache table
		$y=0;
		$apps[$x]['db'][$y]['table']['name'] = "v_bulkvs_numbers_cache";
		$apps[$x]['db'][$y]['table']['parent'] = "";
		$z=0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "bulkvs_numbers_cache_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "tn";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "character varying(20)";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "varchar(20)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "unique";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "status";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "character varying(50)";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "varchar(50)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "activation_date";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamp";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "rate_center";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "character varying(100)";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "varchar(100)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "tier";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "character varying(50)";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "varchar(50)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "lidb";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "character varying(15)";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "varchar(15)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "reference_id";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "character varying(255)";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "varchar(255)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "sms";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "boolean";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "boolean";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "tinyint(1)";
		$apps[$x]['db'][$y]['fields'][$z]['default'] = "false";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "mms";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "boolean";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "boolean";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "tinyint(1)";
		$apps[$x]['db'][$y]['fields'][$z]['default'] = "false";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "portout_pin";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "character varying(10)";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "varchar(10)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "trunk_group";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "character varying(100)";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "varchar(100)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "data_json";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "jsonb";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "last_updated";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamp";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['default'] = "CURRENT_TIMESTAMP";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "created";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamp";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['default'] = "CURRENT_TIMESTAMP";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";

	//schema details - E911 cache table
		$y++;
		$apps[$x]['db'][$y]['table']['name'] = "v_bulkvs_e911_cache";
		$apps[$x]['db'][$y]['table']['parent'] = "";
		$z=0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "bulkvs_e911_cache_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "tn";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "character varying(20)";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "varchar(20)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "unique";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "caller_name";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "character varying(255)";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "varchar(255)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "address_line1";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "character varying(255)";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "varchar(255)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "address_line2";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "character varying(255)";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "varchar(255)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "city";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "character varying(100)";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "varchar(100)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "state";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "character varying(2)";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "varchar(2)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "zip";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "character varying(10)";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "varchar(10)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "address_id";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "character varying(100)";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "varchar(100)";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "sms";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "jsonb";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "data_json";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "jsonb";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "last_updated";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamp";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['default'] = "CURRENT_TIMESTAMP";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "created";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamp";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['default'] = "CURRENT_TIMESTAMP";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";

	//schema details - Sync status table
		$y++;
		$apps[$x]['db'][$y]['table']['name'] = "v_bulkvs_sync_status";
		$apps[$x]['db'][$y]['table']['parent'] = "";
		$z=0;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "bulkvs_sync_status_uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "uuid";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "char(36)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "primary";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "sync_type";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "character varying(20)";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "varchar(20)";
		$apps[$x]['db'][$y]['fields'][$z]['key']['type'] = "unique";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "last_sync_start";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamp";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "last_sync_end";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "timestamp";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "datetime";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "last_record_count";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "numeric";
		$apps[$x]['db'][$y]['fields'][$z]['default'] = "0";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "current_record_count";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "numeric";
		$apps[$x]['db'][$y]['fields'][$z]['default'] = "0";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "sync_in_progress";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "boolean";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "boolean";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "tinyint(1)";
		$apps[$x]['db'][$y]['fields'][$z]['default'] = "false";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "sync_status";
		$apps[$x]['db'][$y]['fields'][$z]['type']['pgsql'] = "character varying(20)";
		$apps[$x]['db'][$y]['fields'][$z]['type']['sqlite'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['type']['mysql'] = "varchar(20)";
		$apps[$x]['db'][$y]['fields'][$z]['default'] = "success";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";
		$z++;
		$apps[$x]['db'][$y]['fields'][$z]['name'] = "error_message";
		$apps[$x]['db'][$y]['fields'][$z]['type'] = "text";
		$apps[$x]['db'][$y]['fields'][$z]['description']['en-us'] = "";

?>
